### ISSUE TITLE
Should you add compatibility with unusual models like gans for example

### ISSUE THREAD

**Issue by hadaev8** [davidtvs/pytorch-lr-finder#16]
In general, I need some wrappers about how batch prcessed and data flow to model.

**Comment by maxbaluev** [comment]
Any updates?

**Comment by davidtvs** [comment]
sadly no, not sure if the algorithm would even provide any meaningful results for things like gans. As far as I know, there's no implementation of this algorithm that supports them. (someone correct me if I'm wrong)

Having said that, I could still give it a try but it won't happen in the near future. PRs are welcome though 😉
