### ISSUE TITLE
Multi-output regression problem

### ISSUE THREAD

**Issue by Stoops-ML** [davidtvs/pytorch-lr-finder#35]
Hi,

My model has several outputs from the forward method:
 ```
def forward(self, x):
        ---code---
        return ClCd, angle
```
This returns a tuple, which LR finder does not like. I get the following error message:
```
if not (target.size() == input.size()):
AttributeError: 'tuple' object has no attribute 'size'
```

Is there a way for LR finder to work with tuples?
Alternatively, should I be structuring the output from my forward method differently (i.e. using a single output tensor)? I tried outputting a single tensor with two columns from my forward method (each column representing an output), but this gave significantly worse results in training.

**Comment by NaleRaphael** [comment]
Hi @Stoops-ML, `LRFinder` should work with tuple input now. Could you please provide more details about the error? (e.g. complete traceback)

And according to the code you given,
```python
if not (target.size() == input.size()):
```
this line does not exist in the source code of this package, could you please check that?

**Comment by NaleRaphael** [comment]
Sorry, I just misunderstood your problem. I'll figure out a solution for you later.

**Comment by Stoops-ML** [comment]
Here's the full traceback:

Traceback (most recent call last):
  File "/Users/danielstoops/Desktop/Work/ML/projects/aerofoils/run_CNN.py", line 142, in <module>
    lr_finder.range_test(train_loader, end_lr=200, num_iter=200)
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_lr_finder/lr_finder.py", line 189, in range_test
    loss = self._train_batch(iter_wrapper, accumulation_steps)
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_lr_finder/lr_finder.py", line 242, in _train_batch
    loss = self.criterion(outputs, labels)
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 782, in forward
    return F.smooth_l1_loss(input, target, reduction=self.reduction)
  File "/usr/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py", line 2153, in smooth_l1_loss
    if not (target.size() == input.size()):
AttributeError: 'tuple' object has no attribute 'size'

The error is coming from the loss function. Because I'm returning a tuple from my forward method, I call two loss functions for every epoch: one for each output. Perhaps the error is that I only provide one loss function to LRFinder()?
`    lr_finder = LRFinder(model, optimiser, criterion, device=device)
`

**Comment by NaleRaphael** [comment]
Well, this would be a little tricky. You have to create a custom `LRFinder` overriding 2 lines of code in `_train_batch()` to make it able work with the output format of your model. See also the example below:

```python
from torch_lr_finder import LRFinder

class MyLRFinder(LRFinder):
    def _train_batch(self, iter_wrapper, accumulation_steps):
        self.model.train()
        total_loss = None

        self.optimizer.zero_grad()
        for i in range(accumulation_steps):
            inputs, labels = next(iter_wrapper)
            inputs, labels = self._move_to_device(inputs, labels)

            # --- Modify these lines according to your `model.forward()` ---
            ... = self.model(inputs)
            loss = self.criterion(..., labels)
            # --------------------------------------------------------------

            loss /= accumulation_steps
            if IS_AMP_AVAILABLE and hasattr(self.optimizer, "_amp_stash"):
                delay_unscale = ((i + 1) % accumulation_steps) != 0

                with amp.scale_loss(
                    loss, self.optimizer, delay_unscale=delay_unscale
                ) as scaled_loss:
                    scaled_loss.backward()
            else:
                loss.backward()

            if total_loss is None:
                total_loss = loss
            else:
                total_loss += loss

        self.optimizer.step()
        return total_loss.item()
```

Currently, there is no easy solution for such case. Since there is no strict convention for the output format of `model.forward()`, what we can do is provide an overridable interface for customization. For such complicated output of `model.forward()`, you can also check out the implementation of [transformers.BertForSequenceClassification][transformers_bert_forward_impl].


[transformers_bert_forward_impl]: https://github.com/huggingface/transformers/blob/6faca88e/src/transformers/modeling_bert.py#L1164

**Comment by NaleRaphael** [comment]
> Because I'm returning a tuple from my forward method, I call two loss functions for every epoch: one for each output.

In this case, you would need to apply those two loss functions in `_train_batch()` as same as they are used in the normal way. e.g.

```python
# --- This is how you train your model ---
for inputs, labels in dataloader:
    inputs, labels = inputs.cuda(), labels.cuda()
    outputs_1, outputs_2 = model(inputs)

    loss_1 = loss_func(outputs_1, labels)
    loss_2 = loss_func(outputs_2, labels)


# --- Then you have to modify `_train_batch()` as the following one ---
class MyLRFinder(LRFinder):
    def _train_batch(self, iter_wrapper, accumulation_steps):
        # ...

        inputs, labels = inputs.cuda(), labels.cuda()
        outputs_1, outputs_2 = model(inputs)
        loss_1 = loss_func(outputs_1, labels)
        loss_2 = loss_func(outputs_2, labels)

        # ...
```

**Comment by NaleRaphael** [comment]
If you want to pick a better learning rate according to the history of multiple loss values, there is a little more work have to be done:

```python
import numpy as np

class MyLRFinder(LRFinder):
    def _train_batch(self, iter_wrapper, accumulation_steps):
        # ...

        inputs, labels = inputs.cuda(), labels.cuda()
        outputs_1, outputs_2 = model(inputs)
        loss_1 = loss_func(outputs_1, labels)
        loss_2 = loss_func(outputs_2, labels)

        # ...

        # Return all loss values
        return loss_1, loss_2

    def range_test(...):
        # ...
        for iteration in tqdm(range(num_iter)):
            # ...

            if iteration == 0:
                self.best_loss = np.array(loss)
            else:
                if smooth_f > 0:
                    loss = smooth_f * loss + (1 - smooth_f) * self.history["loss"][-1]

                mask = loss < self.best_loss
                # Update best loss (even if there is only one value should be updated)
                if any(mask):
                    self.best_loss[mask] = loss[mask]

            # Check if the loss has diverged; if it has, stop the test
            self.history["loss"].append(loss)
            if any(loss > diverge_th * self.best_loss):
                print("Stopping early, the loss has diverged")
                break
        # ...
```

Here is a demonstration of how that mask approach works for multiple values:
```python
prev, curr = np.array([1, 3]), np.array([2, 2])
best = prev.copy()

mask = curr < prev        # array([False,  True])
best[mask] = curr[mask]
print(prev, curr, best)   # [1 3] [2 2] [1 2]
```

@davidtvs, do you think that we should extend `LRFinder` for multiple losses? 🤔

**Comment by Stoops-ML** [comment]
Okay, thanks for the thorough answer. Should I leave this post open, or should I close it?

**Comment by davidtvs** [comment]
So your use case is 1 model, 1 optimizer, and 2 losses? If that's right I think it would be easier and cleaner to wrap the loss functions you are using in a class and pass that to LRFinder. It would be something similar to how [PyTorch defines loss classes](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/loss.py)

Or maybe I didn't fully understand your use case in which case maybe you could provide some more details.

@NaleRaphael I think that if all we want to do is support multiple losses (multiple models or multiple optimizers are not in scope) then wrapping the multiple losses in one and passing that to `LRFinder` should be the best way to go.

**Comment by Stoops-ML** [comment]
Thanks for your reply. That is my use case: 1 model, 1 optimiser, 2 losses. 

I don't fully understand how to wrap the loss functions in a class to pass that to the LRFinder. Could you give me an example please? 

Thanks very much. I hope that this will improve my abilities in Python and PyTorch!

**Comment by NaleRaphael** [comment]
@davidtvs Agree with that. Making a wrapper for multiple loss functions is way more elegant for such case!

@Stoops-ML As it's shown in the link provided by @davidtvs, loss function is also a subclass of `nn.Module`. Therefore, you can simply implement a wrapper like the following one:

```python
class MyLossFunc(nn.Module):
    def __init__(self, ...):
        self.loss_func_1 = ...
        self.loss_func_2 = ...

    def forward(self, inputs, labels):
        loss_1 = self.loss_func_1(inputs, labels)
        loss_2 = self.loss_func_2(inputs, labels)
        return loss_1 + loss_2
```

See also [this post][so_multi_loss] for the reason why it works.


[so_multi_loss]: https://stackoverflow.com/questions/53994625

**Comment by Stoops-ML** [comment]
This worked perfectly. Thank you very much to the both of you for all your time, patience and clear instructions!
