### ISSUE TITLE
How can use this lib for auto-encoders?

### ISSUE THREAD

**Issue by annabeth-h** [davidtvs/pytorch-lr-finder#41]
In manual of this library the examples are for a unified model but auto-encoders are made of two parts:encoder and decoder. How can I use this library for auto-encoder?

**Comment by davidtvs** [comment]
You can always make them a unified model like this:
```py
autoencoder = nn.Sequential(encoder, decoder)
``` 
The above will only work if the output of the encoder is exactly the input of the decoder. The more flexible approach is using a class that inherits from nn.Module:
```py
class Autoencoder(nn.Module):
    def __init__(self):
        super(Autoencoder,self).__init__()        
        self.encoder = encoder
        self.decoder = decoder
    def forward(self,x):
        x = self.encoder(x)
        x = self.decoder(x)
        return x
``` 
After having the unified model using LRFinder is as described in the readme and in the examples.

If you want to train the encoder separately from the decoder, then you would run LRFinder for the encoder and then, separately for the decoder. This way you get two learning rates, one to train the encoder and the other to train the decoder.
