### ISSUE TITLE
Is apex a must have or not?

### ISSUE THREAD

**Issue by gosiqueira** [davidtvs/pytorch-lr-finder#45]
In your README file apex seems to be an optinal requirement.

However, during import time an annoying message warning me that I don't have this module installed keeps poluting my code log.

I tried to reinstall the package using the recommended command and nothing changed at all. I also tried to use warning library to ignore the warning but the way it is implemented is using the Python logging library and I can't remove it this way.

**Comment by NaleRaphael** [comment]
@gosiqueira `apex` is an optional requirement. But I'm sorry about that annoying message, it's supposed to be silenced with the following config (see also [#PR9](https://github.com/davidtvs/pytorch-lr-finder/pull/9#discussion_r360758831)):
```python
# set logging level to ERROR to silence the warning message
import logging
logging.getLogger("torch_lr_finder.lr_finder").setLevel(logging.ERROR)

# warning message "To enable mixed precision training..." won't be shown if apex is not installed
from torch_lr_finder import LRFinder
```

But I didn't notice that current implementation of that warning message might mess up existing logging system, it seems it deserves a better alternative.
I'll make a fix for it later, and thanks for bring it up.

**Comment by gosiqueira** [comment]
Thank you, very much for your fast response. I really appreciate the good job you're doing here.

I'll use your alternative to silence the warning message.

**Comment by gosiqueira** [comment]
Tahnk you very much for answering me in such a short time. I really appreciate the good job you're doing here.

I used the snippet you send here and it worked perfectly. Once again, thank you

**Comment by davidtvs** [comment]
@NaleRaphael has removed the warning and a new release has been deployed with the fix. Closing the issue
