### ISSUE TITLE
Feature Req: Option to disable showing graph and enable saving graph to disk, for purposes of running on headless server

### ISSUE THREAD

**Issue by Shreeyak** [davidtvs/pytorch-lr-finder#53]
As mentioned in title, I'm running experiments on a headless server. Can't view matplotlib graphs. It'd be nice to be able to disable the graphical pop-up (which hangs system till it's closed) and instead save the generated plot to disk. 
The plot could be named by user given string and/or time of generation.

If you prefer/are busy, I can generate a pull request for the same.

**Comment by NaleRaphael** [comment]
Yeah, it's possible in current version of `LRFinder`.

You can create a empty axis object `ax` and pass it into `lr_finder.plot()` to achieve it. See also the example made by @davidtvs in [this comment](https://github.com/davidtvs/pytorch-lr-finder/pull/23#issuecomment-602248697).

Or you can simply save `lr_finder.history` into .json file without running `lr_finder.plot()`, then reload the history from it and plot the graph afterwards.

**Comment by Shreeyak** [comment]
Nice! Even so, it'd be nice to have an parameter in `plot()` to save the figue directly, and to disable drawing the plot itself. Also avoids the user having to import matplotlib.

**Comment by NaleRaphael** [comment]
Yeah, it seems nice to have this feature. Maybe we can wait for @davidtvs to review this idea. 👍

**Comment by davidtvs** [comment]
The example @NaleRaphael linked in his previous comment is from a PR (#23) that suggested implementing that behavior so you can have a look at that PR and see why it was rejected in favor of returning the axis object.

Also, to disable plotting you can also use:
```py
import matplotlib as mpl
mpl.use("Agg")
```

**Comment by Shreeyak** [comment]
Cool, thanks. Would be great to add this functionality to the documentation, maybe even hint at it in the docstring.
