### ISSUE TITLE
Distributed training with ddp

### ISSUE THREAD

**Issue by milliema** [davidtvs/pytorch-lr-finder#64]
Thanks for the work! I'd like to know if distributed training is supported, like the DataParallel and DistributedDataParallel, is it compatible in this work?

**Comment by davidtvs** [comment]
Never tried it, but at first glance, I don't see anything that would stop it from working. Give it a try and let me know if something is broken

**Comment by milliema** [comment]
I've tried DistributedDataParallel, it works well. Not much codes need to be modified, each process will have its own lr_finder instance and the corresponding lr range plot.

**Comment by kio2019** [comment]
> 

could you show u code?
