### ISSUE TITLE
New release for pip?

### ISSUE THREAD

**Issue by carbocation** [davidtvs/pytorch-lr-finder#97]
The current instructions suggest pip-installing, but the (pip-installed code seems to be from 2020](https://pypi.org/project/torch-lr-finder/#history), missing all of the recent changes. It seems to be tracking the package releases, which were last updated in 2020 as well. Can a new release be cut?

**Comment by NaleRaphael** [comment]
The release process is maintained by David, we might need to wait until he is available.
However, if the version information does not quite matter in your use case, you can still get the latest update by:
```bash
# 1. Installing from this git repository directly
$ git clone https://github.com/davidtvs/pytorch-lr-finder
$ cd pytorch-lr-finder
$ pip install .

# 2. Run pip and specify a git URL
$ pip install git+https://github.com/davidtvs/pytorch-lr-finder.git
#    To specific a revision, append a commit hash like this:
$ pip install git+https://github.com/davidtvs/pytorch-lr-finder.git@fd9e949bc709e31881c77a4b0710745524c5091e
```
But please note that the version shown in `$ pip show torch-lr-finder` still depends on [`setup.py`](https://github.com/davidtvs/pytorch-lr-finder/blob/fd9e949bc709e31881c77a4b0710745524c5091e/setup.py#L46).

Hi @davidtvs, here is a brief summary for the new release, hope this could help (hash signs for PR and issue are removed here to avoid adding noise by cross reference):
- Fix issue 65 by explicitly checking `min_grad_idx` is None or not (PR 66)
  - But I might need to work on issue 88 first, it's related to issue 65. (sorry, I missed it on my schedule...)
- Add `torch.amp` as a new backend available for mixed precision training (PR 91)

Within these updates, there are no breaking changes to API. But we added new keyword arguments for selecting backend for mixed precision training in PR 91, so bumping the minor version would be suggested.
If there is any further thing need to be solved before the new release, please feel free to let me know!

**Comment by davidtvs** [comment]
I will create a new release once we merge #98 . Thanks @NaleRaphael for the help!

**Comment by davidtvs** [comment]
New release has been published: https://github.com/davidtvs/pytorch-lr-finder/releases/tag/v0.2.2
